# Generated by Django 3.0.2 on 2020-01-07 02:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('expert_id', models.UUIDField(default=uuid.uuid4, help_text='Do not edit', primary_key=True, serialize=False, unique=True, verbose_name='Expert ID')),
                ('name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('contact_no', models.BigIntegerField(help_text='Contact No OF the Framer', verbose_name='Contact No')),
                ('verified', models.BooleanField(default=False, verbose_name='Verified Account')),
                ('when', models.DateTimeField(auto_now_add=True, help_text='When the account created', verbose_name='When')),
                ('acc', models.OneToOneField(help_text='User Information', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Expert',
                'verbose_name_plural': 'Experts',
            },
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('farmer_id', models.UUIDField(default=uuid.uuid4, help_text='Do Not Edit', primary_key=True, serialize=False, unique=True, verbose_name='Farmer ID')),
                ('name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('contact_no', models.BigIntegerField(help_text='Contact No OF the Framer', verbose_name='Contact No')),
                ('verified', models.BooleanField(default=False, verbose_name='Verified Account')),
                ('when', models.DateTimeField(auto_now_add=True, help_text='When the account created', verbose_name='When')),
                ('acc', models.OneToOneField(help_text='User Information', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Farmer',
                'verbose_name_plural': 'Farmers',
            },
        ),
        migrations.CreateModel(
            name='Verify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_no', models.BigIntegerField(blank=True, help_text='Conatct Numeber of the user', verbose_name='Contact Number')),
                ('token', models.IntegerField(blank=True, help_text='Token for authentication <6 Digits>', verbose_name='Token')),
                ('create_stamp', models.DateTimeField(blank=True, verbose_name='When Created')),
                ('verified', models.BooleanField(default=False, verbose_name='Verified Token')),
                ('change_request', models.BooleanField(default=True, verbose_name='Change Request')),
                ('expert_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tokenexpert', to='Account.Expert', verbose_name='Expert Account')),
                ('farmer_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tokenfarmer', to='Account.Farmer', verbose_name='Farmer Account')),
            ],
        ),
    ]
