# Generated by Django 3.0.2 on 2020-01-07 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
        ('Tomato', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Potato',
            new_name='Tomato',
        ),
    ]
